# syntax=docker/dockerfile:1

# FROM node:12.18.1
FROM node:16.13.2 
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY . .

EXPOSE 8080
CMD [ "node", "server.js" ]
